name = "Better Motherfucking Website"
license = "MIT"
description = "A micro.blog compatible Hugo theme based on bettermotherfuckingwebsite.com. Minimal, readable, and fast."
tags = ["minimal", "microblog", "blog", "responsive", "microformats"]
features = ["microformats2", "json-feed", "webmention", "micropub", "indieauth"]
min_version = "0.91.0"

[author]
  name = "jamwil"
